// packages/product-import-export-plugin/src/ui/components/export-dialog.component.ts
import { Component, ViewChild, ElementRef, AfterViewInit, OnInit } from '@angular/core'
import { Dialog } from '@vendure/admin-ui/core'
import { FormsModule } from '@angular/forms'
import { SharedModule } from '@vendure/admin-ui/core'
import { uniq } from 'lodash'

type ProductFields =
  | 'name'
  | 'slug'
  | 'description'
  | 'assets'
  | 'facets'
  | 'optionGroups'

type VariantFields =
  | 'sku'
  | 'optionValues'
  | 'price'
  | 'taxCategory'
  | 'stockOnHand'
  | 'trackInventory'
  | 'variantAssets'
  | 'variantFacets'
  | 'enabled'

type ExportFields = Array<ProductFields | VariantFields>
interface PluginInitOptions {
  defaultFileName?: string
  exportAssetsAsOptions?: Array<'url' | 'json'>
  defaultExportAssetsAs?: 'url' | 'json'
  defaultExportFields?: ExportFields
  requiredExportFields?: ExportFields
}

@Component({
  selector: 'vdr-export-dialog',
  templateUrl: './export-dialog.component.html',
  standalone: true,
  imports: [SharedModule, FormsModule],
})
export class ExportDialogComponent
  implements
    Dialog<{
      result: boolean
      fileName?: string
      selectedFields?: string[]
      exportAssetsAs?: 'url' | 'json'
      selectedExportFields?: ExportFields
    }>,
    AfterViewInit,
    OnInit
{
  private mandatoryOptionFields: Array<ProductFields | VariantFields> = ['optionGroups', 'optionValues']
  @ViewChild('fileNameInput', { static: false }) fileNameElement: ElementRef<HTMLInputElement>

  resolveWith: (result?: {
    result: boolean
    fileName?: string
    selectedFields?: string[]
    exportAssetsAs?: 'url' | 'json'
    selectedExportFields?: ExportFields
  }) => void
  selection: any[] = []
  fileName = ''
  customFields: string[] = []
  selectedFields: string[] = []
  exportAssetsAs: 'url' | 'json' = 'url'
  selectedExportFields: ExportFields = []
  availableExportFields: ExportFields = [
    'name',
    'slug',
    'description',
    'assets',
    'facets',
    'optionGroups',
    'sku',
    'optionValues',
    'price',
    'taxCategory',
    'stockOnHand',
    'trackInventory',
    'variantAssets',
    'variantFacets',
    'enabled',
  ]

  config: PluginInitOptions
  toggleAllChecked = false

  ngOnInit(): void {
    this.selectedFields = [...this.customFields]
    if (this.config.defaultExportAssetsAs?.includes(this.config.defaultExportAssetsAs)) {
      this.exportAssetsAs = this.config.defaultExportAssetsAs
    } else {
      this.exportAssetsAs = this.config.exportAssetsAsOptions?.[0] || 'url'
    }

    this.selectedExportFields = uniq([
      ...(this.config.defaultExportFields || []),
      ...(this.config.requiredExportFields || []),
      ...this.mandatoryOptionFields,
    ])
  }

  ngAfterViewInit(): void {
    if (this.fileNameElement) {
      setTimeout(() => {
        this.fileNameElement.nativeElement.focus()
      }, 0)
    }
  }

  export() {
    this.fileName = this.fileName?.trim()
    this.resolveWith({
      result: true,
      fileName: this.fileName,
      selectedFields: this.selectedFields,
      exportAssetsAs: this.exportAssetsAs,
      selectedExportFields: this.selectedExportFields,
    })
  }

  cancel() {
    this.resolveWith({ result: false })
  }

  toggleFieldSelection(fieldName: string) {
    const index = this.selectedFields.indexOf(fieldName)
    if (index > -1) {
      this.selectedFields.splice(index, 1)
    } else {
      this.selectedFields.push(fieldName)
    }

    this.toggleAllChecked = this.selectedFields.length === this.availableExportFields.length
  }

  toggleExportFieldSelection(fieldName: ProductFields | VariantFields) {
    if (this.mandatoryOptionFields.includes(fieldName)) {
      return
    }
    const index = this.selectedExportFields.indexOf(fieldName)
    if (index > -1) {
      this.selectedExportFields.splice(index, 1)
    } else {
      this.selectedExportFields.push(fieldName)
    }

    this.toggleAllChecked = this.selectedExportFields.length === this.availableExportFields.length
  }

  toggleSelectAll(event: Event) {
    const isChecked = (event.target as HTMLInputElement).checked
    this.toggleAllChecked = isChecked
    if (isChecked) {
      this.selectedExportFields = [...this.availableExportFields]
      this.selectedFields = [...this.customFields]
    } else {
      this.selectedExportFields = [
        ...this.availableExportFields.filter((field) =>
          this.config.requiredExportFields?.includes(field),
        ),
        ...this.mandatoryOptionFields,
      ]
      this.selectedFields = []
    }
  }

  isMandatoryExportField(field: ProductFields | VariantFields): boolean {
    return this.mandatoryOptionFields.includes(field)
  }
}

<ng-template vdrDialogTitle>{{ 'product-export.dialog.title' | translate }}</ng-template>
<div class="input-row">
  <vdr-form-field [label]="'product-export.dialog.label' | translate">
    <input
      type="text"
      [(ngModel)]="fileName"
      [placeholder]="config?.defaultFileName || 'products_export.csv'"
      style="width: 100%"
      #fileNameInput
    />
  </vdr-form-field>
</div>

<div class="input-row" style="margin-top: 16px">
  <input type="checkbox" (change)="toggleSelectAll($event)" [checked]="toggleAllChecked" />
  {{ 'product-export.dialog.selectAll' | translate }}
</div>

<div class="input-row" style="margin-top: 16px">
  <label style="margin-bottom: 8px; display: inline-block">{{
    'product-export.dialog.availableExportFieldsLabel' | translate
  }}</label>
  <div *ngFor="let field of availableExportFields">
    <input
      type="checkbox"
      [value]="field"
      (change)="toggleExportFieldSelection(field)"
      [checked]="selectedExportFields.includes(field)"
      [disabled]="config.requiredExportFields.includes(field) || isMandatoryExportField(field)"
    />
    {{ field }}
  </div>
</div>

<div class="input-row" style="margin-top: 16px">
  <label style="margin-bottom: 8px; display: inline-block">{{
    'product-export.dialog.customFieldsLabel' | translate
  }}</label>
  <div *ngFor="let field of customFields">
    <input
      type="checkbox"
      [value]="field"
      (change)="toggleFieldSelection(field)"
      [checked]="selectedFields.includes(field)"
    />
    {{ field }}
  </div>
</div>

<span style="margin-top: 16px; margin-bottom: 8px; display: block">{{
  'product-export.dialog.exportAssetsAs' | translate
}}</span>
<div class="input-row" style="margin-top: 8px">
  <label *ngIf="config?.exportAssetsAsOptions?.includes('url')">
    <input
      type="radio"
      name="exportAssets"
      value="url"
      [(ngModel)]="exportAssetsAs"
      style="width: fit-content"
    />
    {{ 'product-export.dialog.exportAssetsAsOptions.url' | translate }}
  </label>
  <label *ngIf="config?.exportAssetsAsOptions?.includes('json')">
    <input
      type="radio"
      name="exportAssets"
      value="json"
      [(ngModel)]="exportAssetsAs"
      style="width: fit-content"
    />
    {{ 'product-export.dialog.exportAssetsAsOptions.json' | translate }}
  </label>
</div>

<ng-template vdrDialogButtons>
  <button type="button" class="btn" (click)="cancel()">
    {{ 'common.cancel' | translate }}
  </button>
  <button type="button" class="btn btn-primary" (click)="export()">
    {{ 'product-export.dialog.export' | translate }}
  </button>
</ng-template>

// packages/product-import-export-plugin/src/dashboard/export-dialog.tsx
import {
  Button,
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  Input,
  Label,
  RadioGroup,
  RadioGroupItem,
  Checkbox,
  toast,
} from '@vendure/dashboard'
import { useState, useEffect } from 'react'
import {
  getServerLocation,
  getChannelHeader,
  type PluginInitOptions,
  type ExportFields,
  type ProductFields,
  type VariantFields,
} from './utils'

interface ExportDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  productIds: string[]
  isExportAll?: boolean
}

export function ExportDialog({
  open,
  onOpenChange,
  productIds,
  isExportAll = false,
}: ExportDialogProps) {
  const mandatoryOptionFields: Array<ProductFields | VariantFields> = [
    'optionGroups',
    'optionValues',
  ]
  const [fileName, setFileName] = useState('')
  const [customFields, setCustomFields] = useState<string[]>([])
  const [selectedFields, setSelectedFields] = useState<string[]>([])
  const [exportAssetsAs, setExportAssetsAs] = useState<'url' | 'json'>('url')
  const [selectedExportFields, setSelectedExportFields] = useState<ExportFields>([])
  const [availableExportFields] = useState<ExportFields>([
    'name',
    'slug',
    'description',
    'assets',
    'facets',
    'optionGroups',
    'sku',
    'optionValues',
    'price',
    'taxCategory',
    'stockOnHand',
    'trackInventory',
    'variantAssets',
    'variantFacets',
    'enabled',
  ])
  const [config, setConfig] = useState<PluginInitOptions['exportOptions'] | null>(null)
  const [toggleAllChecked, setToggleAllChecked] = useState(false)

  useEffect(() => {
    const fetchConfig = async () => {
      try {
        const serverPath = getServerLocation()
        const [configRes, customFieldsRes] = await Promise.all([
          fetch(`${serverPath}/product-import-export/config`, {
            method: 'GET',
            headers: {
              'Content-Type': 'application/json',
              ...getChannelHeader(),
            },
            credentials: 'include',
          }),
          fetch(`${serverPath}/product-export/custom-fields`, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              ...getChannelHeader(),
            },
            credentials: 'include',
            body: JSON.stringify(productIds.length > 0 ? productIds : []),
          }),
        ])

        const configData = await configRes.json()
        const customFieldsData = await customFieldsRes.json()

        setConfig(configData.exportOptions)
        setCustomFields(customFieldsData.map((field: { name: string }) => field.name))
        setSelectedFields([...customFieldsData.map((field: { name: string }) => field.name)])
        setExportAssetsAs(
          configData.exportOptions?.defaultExportAssetsAs ||
            configData.exportOptions?.exportAssetsAsOptions?.[0] ||
            'url',
        )
        if (
          configData.exportOptions?.defaultExportFields ||
          configData.exportOptions?.requiredExportFields
        ) {
          setSelectedExportFields(
            Array.from(
              new Set([
                ...(configData.exportOptions.defaultExportFields || []),
                ...(configData.exportOptions.requiredExportFields || []),
                ...mandatoryOptionFields,
              ]),
            ) as ExportFields,
          )
        }
      } catch (error) {
        console.error('Failed to fetch config:', error)
      }
    }

    if (open) {
      fetchConfig()
    }
  }, [open, productIds])

  const toggleFieldSelection = (fieldName: string) => {
    setSelectedFields((prev) =>
      prev.includes(fieldName) ? prev.filter((f) => f !== fieldName) : [...prev, fieldName],
    )
  }

  const toggleExportFieldSelection = (fieldName: ProductFields | VariantFields) => {
    if (mandatoryOptionFields.includes(fieldName)) {
      return
    }
    setSelectedExportFields((prev) =>
      prev.includes(fieldName) ? prev.filter((f) => f !== fieldName) : [...prev, fieldName],
    )
  }

  const toggleSelectAll = (checked: boolean) => {
    setToggleAllChecked(checked)
    if (checked) {
      setSelectedExportFields([...availableExportFields])
      setSelectedFields([...customFields])
    } else {
      setSelectedExportFields([...(config?.requiredExportFields || []), ...mandatoryOptionFields])
      setSelectedFields([])
    }
  }

  const handleExport = async () => {
    const trimmedFileName = fileName.trim()
    const finalFileName = trimmedFileName || config?.defaultFileName || 'products_export.csv'

    try {
      const serverPath = getServerLocation()
      const endpoint = isExportAll ? 'export-all' : 'export'
      const body = isExportAll ? undefined : JSON.stringify(productIds)

      const res = await fetch(
        `${serverPath}/product-export/${endpoint}?fileName=${encodeURIComponent(finalFileName)}&customFields=${encodeURIComponent(selectedFields.join(','))}&exportAssetsAs=${exportAssetsAs}&selectedExportFields=${encodeURIComponent(selectedExportFields.join(','))}`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            ...getChannelHeader(),
          },
          credentials: 'include',
          ...(body && { body }),
        },
      )

      if (!res.ok) {
        const json = await res.json()
        throw new Error(json?.message || 'Export failed')
      }

      onOpenChange(false)
      toast.success(
        `Export job queued successfully. ${
          isExportAll ? 'All' : productIds.length
        } products will be exported.`,
      )
    } catch (error: unknown) {
      console.error(error)
      toast.error((error as Error)?.message || 'Failed to queue export')
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Export products to CSV</DialogTitle>
          <DialogDescription>Configure export settings</DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          <div>
            <Label htmlFor="file-name">File name (optional)</Label>
            <p className="text-sm text-muted-foreground mt-1">
              A timestamp will be automatically added to the filename to ensure uniqueness.
            </p>
            <Input
              id="file-name"
              value={fileName}
              onChange={(e) => setFileName(e.target.value)}
              placeholder={config?.defaultFileName || 'products_export.csv'}
              className="mt-1"
            />
          </div>

          <div>
            <Label>Select fields to export</Label>
            <div className="flex items-center space-x-2 mt-2">
              <Checkbox
                id="select-all"
                checked={toggleAllChecked}
                onCheckedChange={(checked) => toggleSelectAll(checked as boolean)}
              />
              <Label htmlFor="select-all" className="font-normal">
                Select all
              </Label>
            </div>
            <div className="grid grid-cols-2 gap-2 mt-2">
              {availableExportFields.map((field) => (
                <div key={field} className="flex items-center space-x-2">
                  <Checkbox
                    id={`field-${field}`}
                    checked={selectedExportFields.includes(field)}
                    onCheckedChange={() => toggleExportFieldSelection(field)}
                    disabled={
                      config?.requiredExportFields?.includes(field) ||
                      mandatoryOptionFields.includes(field)
                    }
                  />
                  <Label htmlFor={`field-${field}`} className="font-normal">
                    {field}
                  </Label>
                </div>
              ))}
            </div>
            {customFields.length > 0 && (
              <div className="grid grid-cols-2 gap-2 mt-2">
                {customFields.map((field) => (
                  <div key={field} className="flex items-center space-x-2">
                    <Checkbox
                      id={`custom-${field}`}
                      checked={selectedFields.includes(field)}
                      onCheckedChange={() => toggleFieldSelection(field)}
                    />
                    <Label htmlFor={`custom-${field}`} className="font-normal">
                      {field}
                    </Label>
                  </div>
                ))}
              </div>
            )}
          </div>

          <div>
            <Label>Export assets as:</Label>
            <RadioGroup
              value={exportAssetsAs}
              onValueChange={(val) => setExportAssetsAs(val as 'url' | 'json')}
              className="mt-2"
            >
              {config?.exportAssetsAsOptions?.includes('url') && (
                <div className="flex items-center space-x-2">
                  <RadioGroupItem value="url" id="assets-url" />
                  <Label htmlFor="assets-url" className="font-normal">
                    URL
                  </Label>
                </div>
              )}
              {config?.exportAssetsAsOptions?.includes('json') && (
                <div className="flex items-center space-x-2">
                  <RadioGroupItem value="json" id="assets-json" />
                  <Label htmlFor="assets-json" className="font-normal">
                    JSON
                  </Label>
                </div>
              )}
            </RadioGroup>
          </div>
        </div>

        <DialogFooter>
          <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button type="button" onClick={handleExport}>
            Export
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
